# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QToolTip,
    QPushButton, QApplication)
from PyQt5.QtGui import QFont


class Ui_Form(QtWidgets.QWidget):

    def __init__(self):
        super().__init__()

        self.setupUi(QtWidgets)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1026, 584)
        self.forwardBtn = QtWidgets.QPushButton(Form)
        self.forwardBtn.setGeometry(QtCore.QRect(130, 337, 93, 51))
        self.forwardBtn.setObjectName("forwardBtn")
        self.backwardBtn = QtWidgets.QPushButton(Form)
        self.backwardBtn.setGeometry(QtCore.QRect(130, 427, 93, 51))
        self.backwardBtn.setObjectName("backwardBtn")
        self.rightBtn = QtWidgets.QPushButton(Form)
        self.rightBtn.setGeometry(QtCore.QRect(250, 377, 93, 51))
        self.rightBtn.setObjectName("rightBtn")
        self.leftBtn = QtWidgets.QPushButton(Form)
        self.leftBtn.setGeometry(QtCore.QRect(10, 377, 93, 51))
        self.leftBtn.setObjectName("leftBtn")
        self.upBtn = QtWidgets.QPushButton(Form)
        self.upBtn.setGeometry(QtCore.QRect(810, 327, 93, 61))
        self.upBtn.setObjectName("upBtn")
        self.downBtn = QtWidgets.QPushButton(Form)
        self.downBtn.setGeometry(QtCore.QRect(810, 510, 93, 51))
        self.downBtn.setObjectName("downBtn")
        self.batteryPercentage = QtWidgets.QProgressBar(Form)
        self.batteryPercentage.setGeometry(QtCore.QRect(30, 20, 201, 41))
        self.batteryPercentage.setProperty("value", 24)
        self.batteryPercentage.setObjectName("batteryPercentage")
        self.counterclockwiseBtn = QtWidgets.QPushButton(Form)
        self.counterclockwiseBtn.setGeometry(QtCore.QRect(630, 420, 181, 61))
        self.counterclockwiseBtn.setObjectName("counterclockwiseBtn")
        self.clockwiseBtn = QtWidgets.QPushButton(Form)
        self.clockwiseBtn.setGeometry(QtCore.QRect(890, 420, 131, 61))
        self.clockwiseBtn.setObjectName("clockwiseBtn")
        self.setSpeedSlider = QtWidgets.QSlider(Form)
        self.setSpeedSlider.setGeometry(QtCore.QRect(390, 250, 160, 22))
        self.setSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.setSpeedSlider.setObjectName("setSpeedSlider")
        self.speedVal = QtWidgets.QLCDNumber(Form)
        self.speedVal.setGeometry(QtCore.QRect(350, 70, 281, 171))
        self.speedVal.setObjectName("speedVal")
        self.takeoffBtn = QtWidgets.QPushButton(Form)
        self.takeoffBtn.setGeometry(QtCore.QRect(450, 320, 80, 61))
        self.takeoffBtn.setObjectName("takeoffBtn")
        self.landBtn = QtWidgets.QPushButton(Form)
        self.landBtn.setGeometry(QtCore.QRect(450, 440, 80, 61))
        self.landBtn.setObjectName("landBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.forwardBtn.setText(_translate("Form", "Forward"))
        self.backwardBtn.setText(_translate("Form", "Backward"))
        self.rightBtn.setText(_translate("Form", "Right"))
        self.leftBtn.setText(_translate("Form", "Left"))
        self.upBtn.setText(_translate("Form", "Up"))
        self.downBtn.setText(_translate("Form", "Down"))
        self.counterclockwiseBtn.setText(_translate("Form", "Rotate Counter-clockwise"))
        self.clockwiseBtn.setText(_translate("Form", "Rotate Clockwise"))
        self.takeoffBtn.setText(_translate("Form", "Takeoff"))
        self.landBtn.setText(_translate("Form", "Land"))

def main():

    app = QApplication(sys.argv)
    ex = Ui_Form()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()